/**
 * Barrel re-export — hooks in lib/hooks/useAdmin.ts, services in
 * lib/services/admin.ts. This file keeps old @lib/admin imports working.
 */
export {
  createSubject,
  deleteSubject,
  deleteWaitlist,
  setAdmin,
  setGolden,
  setHint,
  setPotdNote,
  setPremium,
  SUBJECT_CATEGORIES,
  updateSubject,
  type AdminDrop,
  type AdminPotd,
  type AdminToday,
  type AnalyticsCrown,
  type AnalyticsDaily,
  type AnalyticsData,
  type AnalyticsTotals,
  type AuditEntry,
  type EngagementDaily,
  type EngagementData,
  type EngagementTotals,
  type Frame,
  type Member,
  type RecentSubmission,
  type ReportEntry,
  type Subject,
  type SubjectCategory,
  type WaitlistEntry,
} from "./services/admin";
export {
  useAdminToday,
  useAnalytics,
  useAuditFeed,
  useEngagement,
  useFrames,
  useIsAdmin,
  useMembers,
  useRecentSubmissions,
  useReports,
  useSubjects,
  useWaitlist,
} from "./hooks/useAdmin";
